library(dplyr)
library(ggplot2)
library(ggthemes)
library(Rgb)
library(survey)
library(janitor)


BRHD_cols <- list(rgb(0, 141, 168, maxColorValue = 255), rgb(241, 227, 197, maxColorValue = 255),
                  rgb(212, 69, 29, maxColorValue = 255), rgb(102, 51, 52, maxColorValue = 255),
                  rgb(255, 206, 113, maxColorValue = 255), rgb(109, 39, 106, maxColorValue = 255),
                  rgb(231, 65, 122, maxColorValue = 255), rgb(0,0,0), maxColorValue = 255)
BRHD_cols
phwins <- read.csv("phwins.csv", header = TRUE)

#Clean data to be prepared for analysis, from https://www.r-bloggers.com/2021/04/how-to-clean-the-datasets-in-r/
#Clean variable names
phwins <- clean_names(phwins)
#Set blank cells to "NA"
phwins <- phwins %>% mutate_all(na_if,"")

#Check tables for specific questions
tabyl(phwins,a_goals)
tabyl(phwins,b_work_imp)
tabyl(phwins,c_creatvty)
tabyl(phwins,d_communctn)
tabyl(phwins,e_suprvsr_emplyee_bkgrnd)
tabyl(phwins,f_sprvsr_emplyeee_dev)
tabyl(phwins,g_training)
tabyl(phwins,h_emplyee_tech)
tabyl(phwins,i_emplyee_learn)
tabyl(phwins,j_suprvsr_ldrship)
tabyl(phwins,k_oppur_postn)
tabyl(phwins,l_work_involvmnt)
tabyl(phwins,m_effort)
tabyl(phwins,n_talnts_expertse)
tabyl(phwins,o_work_reltnshp)
tabyl(phwins,p_suprvsr_respct)
tabyl(phwins,q_brhd_work)
tabyl(phwins,r_brhd_edia)
tabyl(phwins,a_job)
tabyl(phwins,b_brhd)
tabyl(phwins,c_pay)
tabyl(phwins,d_job_secrty)
#tabyl(phwins,qlt_workplace)
tabyl(phwins,a_ph_harrass)
tabyl(phwins,b_out_brhd)
tabyl(phwins,ment_health)
tabyl(phwins,a_covid_ment)
tabyl(phwins,b_covid_situtn)
tabyl(phwins,c_covid_strtld)
tabyl(phwins,d_numb)
tabyl(phwins,a_covid_job)
tabyl(phwins,a_leaving_brhd)
tabyl(phwins,b_levng_brhd_when)
tabyl(phwins,c_new_postn)
tabyl(phwins,d_hr)
tabyl(phwins,e_school)
tabyl(phwins,f_degree)
tabyl(phwins,g_aftr_eductn)
#tabyl(phwins,a_styng_brhd)
#tabyl(phwins,b_reson_levng_brhd)
tabyl(phwins,retire)
tabyl(phwins,emplou_status)
tabyl(phwins,covid_role)
tabyl(phwins,a_covid_hire)#Needs cleaning
tabyl(phwins,b_q_one_covid)#Needs cleaning
tabyl(phwins,b_q_two_covid)#Needs cleaning
tabyl(phwins,b_q_three_covid)#Needs cleaning
tabyl(phwins,b_q_four_covid)#Needs cleaning
tabyl(phwins,b_q_one_covid_new)#Needs cleaning
tabyl(phwins,b_q_two_covid_new)#Needs cleaning
tabyl(phwins,b_q_three_covid_new)#Needs cleaning
tabyl(phwins,b_q_four_covid_new)#Needs cleaning
tabyl(phwins,b_q_one_covid_new_lst)#Needs cleaning
tabyl(phwins,c_hours)#Needs different summary method
#tabyl(phwins,covid_issues)
#tabyl(phwins,qlt_covid_brhd)
tabyl(phwins,service_area)
tabyl(phwins,suprvsr_status)
tabyl(phwins,a_non_sup_commnctn)
tabyl(phwins,a_non_sup_comnctn_others)
tabyl(phwins,a_non_sup_source_data)
tabyl(phwins,a_non_sup_data)
tabyl(phwins,a_non_sup_evidence)
tabyl(phwins,a_non_sup_diverse)
tabyl(phwins,a_non_sup_edia)
tabyl(phwins,a_non_sup_custmr)
tabyl(phwins,a_non_sup_finance) 
tabyl(phwins,a_non_sup_fundn_mech) 
tabyl(phwins,a_non_sup_tool)
tabyl(phwins,a_non_sup_org_prctce)
tabyl(phwins,a_non_sup_external)
tabyl(phwins,a_non_sup_sdh)
tabyl(phwins,a_non_sup_qlty_imprv)
tabyl(phwins,a_non_sup_cha)
tabyl(phwins,a_non_sup_mission)
tabyl(phwins,a_non_sup_comny_partners)
tabyl(phwins,a_non_sup_comnty_assts)
tabyl(phwins,a_non_sup_across)
tabyl(phwins,a_non_sup_hlt_comnty)
tabyl(phwins,a_non_sup_policy)
tabyl(phwins,a_non_sup_col_info)
tabyl(phwins,b_non_sup_commnctn)
tabyl(phwins,b_non_sup_comnctn_others)
tabyl(phwins,b_non_sup_source_data)
tabyl(phwins,b_non_sup_data)
tabyl(phwins,b_non_sup_evidence)
tabyl(phwins,b_non_sup_diverse)
tabyl(phwins,b_non_sup_edia)
tabyl(phwins,b_non_sup_custmr)
tabyl(phwins,b_non_sup_finance)
tabyl(phwins,b_non_sup_fundn_mech)
tabyl(phwins,b_non_sup_tool)
tabyl(phwins,b_non_sup_org_prctce)
tabyl(phwins,b_non_sup_external)
tabyl(phwins,b_non_sup_sdh)
tabyl(phwins,b_non_sup_qlty_imprv)
tabyl(phwins,b_non_sup_cha)
tabyl(phwins,b_non_sup_mission)
tabyl(phwins,b_non_sup_comny_partners)
tabyl(phwins,b_non_sup_comnty_assts)
tabyl(phwins,b_non_sup_across)
tabyl(phwins,b_non_sup_hlt_comnty)
tabyl(phwins,b_non_sup_policy)
tabyl(phwins,b_non_sup_col_info)
tabyl(phwins,sup_years)
tabyl(phwins,c_sup_commnctn)
tabyl(phwins,c_sup_comnctn_others)
tabyl(phwins,c_sup_source_data)
tabyl(phwins,c_sup_data)
tabyl(phwins,c_sup_evidence)
tabyl(phwins,c_sup_diverse)
tabyl(phwins,c_sup_edia)
tabyl(phwins,c_sup_custmr)
tabyl(phwins,c_sup_finance)
tabyl(phwins,c_sup_fundn_mech)
tabyl(phwins,c_sup_tool)
tabyl(phwins,c_sup_org_prctce)
tabyl(phwins,c_sup_external)
tabyl(phwins,c_sup_trends)
tabyl(phwins,c_sup_sdh)
tabyl(phwins,c_sup_qlty_imprv)
tabyl(phwins,c_sup_cha)
tabyl(phwins,c_sup_mission)
tabyl(phwins,c_sup_comny_partners)
tabyl(phwins,c_sup_comnty_assts)
tabyl(phwins,c_sup_across)
tabyl(phwins,c_sup_hlt_comnty)
tabyl(phwins,c_sup_policy)
tabyl(phwins,c_sup_col_info)
tabyl(phwins,d_sup_commnctn)
tabyl(phwins,d_sup_comnctn_others)
tabyl(phwins,d_sup_source_data)
tabyl(phwins,d_sup_data)
tabyl(phwins,d_sup_evidence)
tabyl(phwins,d_sup_diverse)
tabyl(phwins,d_sup_edia)
tabyl(phwins,d_sup_custmr)
tabyl(phwins,d_sup_finance)
tabyl(phwins,d_sup_fundn_mech)
tabyl(phwins,d_sup_tool)
tabyl(phwins,d_sup_org_prctce)
tabyl(phwins,d_sup_external)
tabyl(phwins,d_sup_trends)
tabyl(phwins,d_sup_sdh)
tabyl(phwins,d_sup_qlty_imprv)
tabyl(phwins,d_sup_cha)
tabyl(phwins,d_sup_mission)
tabyl(phwins,d_sup_comny_partners)
tabyl(phwins,d_sup_comnty_assts)
tabyl(phwins,d_sup_across)
tabyl(phwins,d_sup_hlt_comnty)
tabyl(phwins,d_sup_policy)
tabyl(phwins,d_sup_col_info)
tabyl(phwins,executve_years)
tabyl(phwins,e_exe_commnctn)
tabyl(phwins,e_exe_comnctn_others)
tabyl(phwins,e_exe_source_data)
tabyl(phwins,e_exe_data)
tabyl(phwins,e_exe_evidence)
tabyl(phwins,e_exe_diverse)
tabyl(phwins,e_exe_edia)
tabyl(phwins,e_exe_custmr)
tabyl(phwins,e_exe_finance)
tabyl(phwins,e_exe_fundn_mech)
tabyl(phwins,e_exe_tool)
tabyl(phwins,e_exe_org_prctce)
tabyl(phwins,e_exe_external)
tabyl(phwins,e_exe_trends)
tabyl(phwins,e_exe_sdh)
tabyl(phwins,e_exe_qlty_imprv)
tabyl(phwins,e_exe_cha)
tabyl(phwins,e_exe_mission)
tabyl(phwins,e_exe_comny_partners)
tabyl(phwins,e_exe_comnty_assts)
tabyl(phwins,e_exe_across)
tabyl(phwins,e_exe_hlt_comnty)
tabyl(phwins,e_exe_policy)
tabyl(phwins,e_exe_col_info)
tabyl(phwins,f_exe_commnctn)
tabyl(phwins,f_exe_comnctn_others)
tabyl(phwins,f_exe_source_data)
tabyl(phwins,f_exe_data)
tabyl(phwins,f_exe_evidence)
tabyl(phwins,f_exe_diverse)
tabyl(phwins,f_exe_edia)
tabyl(phwins,f_exe_custmr)
tabyl(phwins,f_exe_finance)
tabyl(phwins,f_exe_fundn_mech)
tabyl(phwins,f_exe_tool)
tabyl(phwins,f_exe_org_prctce)
tabyl(phwins,f_exe_external)
tabyl(phwins,f_exe_trends)
tabyl(phwins,f_exe_sdh)
tabyl(phwins,f_exe_qlty_imprv)
tabyl(phwins,f_exe_cha)
tabyl(phwins,f_exe_mission)
tabyl(phwins,f_exe_comny_partners)
tabyl(phwins,f_exe_comnty_assts)
tabyl(phwins,f_exe_across)
tabyl(phwins,f_exe_hlt_comnty)
tabyl(phwins,f_exe_policy)
tabyl(phwins,f_exe_col_info)
tabyl(phwins,he)
tabyl(phwins,sde)
tabyl(phwins,sdh)
tabyl(phwins,sr)
tabyl(phwins,ej)
tabyl(phwins,he_1)
tabyl(phwins,sde_1)
tabyl(phwins,sdh_1)
tabyl(phwins,sr_1)
tabyl(phwins,ej_1)
tabyl(phwins,racism)
tabyl(phwins,racism_1)
tabyl(phwins,racsm_crisis)
#tabyl(phwins,racism_2)
phwins %>% tabyl(gender) %>% adorn_pct_formatting(digits = 2, affix_sign = TRUE) %>% adorn_totals()
phwins %>% tabyl(ethnicity) %>% adorn_pct_formatting(digits = 2, affix_sign = TRUE) %>% adorn_totals()
phwins %>% tabyl(race) %>% adorn_pct_formatting(digits = 2, affix_sign = TRUE) %>% adorn_totals()
phwins %>% tabyl(age) %>% adorn_pct_formatting(digits = 2, affix_sign = TRUE) %>% adorn_totals()
tabyl(phwins,age)#Needs cleaning
tabyl(phwins,years_positn)#Needs cleaning
tabyl(phwins,b_brhd_long)#Needs cleaning
tabyl(phwins,c_ph_pract)#Needs cleaning
tabyl(phwins,employ_status)
tabyl(phwins,employmet_ft)
tabyl(phwins,degrees)#Needs cleaning
tabyl(phwins,current_degrees)
tabyl(phwins,b_major)#Needs cleaning
tabyl(phwins,credentials)#Needs cleaning

write.csv(phwins, "C:/Users/charrison/Desktop/RWD/phwins.csv")

count(phwins$c_ph_pract <=5)
class(phwins$c_ph_pract)

#Using survey package from https://cran.r-project.org/web/packages/survey/survey.pdf, 
#also see useful guide on this package and step-by-step survey analysis at https://stats.oarc.ucla.edu/r/seminars/survey-data-analysis-with-r/
phwins <- svydesign(ids = ~0, probs = NULL, strata = NULL, variables = phwins, fpc = NULL, 
          weights = NULL, nest = FALSE, check.strata = FALSE, pps= FALSE)





q1a <- ggplot(phwins, aes(x =a_goals)) +
  geom_bar(color="steelblue", fill = "steelblue") +
  theme_classic() +
  labs(title = "I know how my work relates to the department's goals and priorities", y="Count") +
  theme(axis.title.x=element_blank())+
  scale_x_discrete(limits=c("Strongly Disagree","Disagree","Neither agree nor disagree","Agree","Strongly agree"))

q1b <- ggplot(phwins, aes(x =b_work_imp)) +
  geom_bar(color="steelblue", fill = "steelblue") +
  theme_classic() +
  labs (title = "The work I do is important",y="Count") +
  theme(axis.title.x=element_blank())+
  scale_x_discrete(limits=c("Strongly Disagree","Disagree","Neither agree nor disagree","Agree","Strongly agree"))
q1b

svytable(~a_goals)
